name       : haskell-cabal-file-th
version    : 0.2.6
release    : 3
source     :
    - https://hackage.haskell.org/package/cabal-file-th-0.2.6/cabal-file-th-0.2.6.tar.gz : dc06f84889253b1d5e6d2859906283adc823f775091cee3155c0eabafa49554d
license    : BSD-3-Clause
component  : programming.haskell
summary    : Template Haskell expressions for reading fields from a project's cabal file.
description: |
    Template Haskell expressions for reading fields from a project's cabal file.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
