name       : haskell-cabal-file-th
version    : 0.2.4
release    : 2
source     :
    - https://hackage.haskell.org/package/cabal-file-th-0.2.4/cabal-file-th-0.2.4.tar.gz : 0b55d7ffacd0c6324fa7c8b8f148e788e6b899fb9bf8795285dea66575bed91c
license    : BSD-3-Clause
component  : programming.haskell
summary    : Template Haskell expressions for reading fields from a project's cabal
    file.
description: |
    Template Haskell expressions for reading fields from a project's cabal file.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
